name: Run My Daily Bot

on:
  schedule:
    # 01:00 UTC = 08:00 AM (8 โมงเช้าเวลาไทย)
    - cron: '0 1 * * *'
  workflow_dispatch: # ทำให้เรามีปุ่มกดรันเองได้ด้วย

jobs:
  run-bot-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Run my Python script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python main.py
